### ISSUE TITLE
find_package is case sensitive

### ISSUE THREAD

**Issue by daviddoria** [libamqp/libamqp#1]
I found your FindUnitTest++.cmake file, very nice! (I've suggested to the UnitTest++ team that the include the file with their release: http://code.google.com/p/unittestpp/issues/detail?id=22&thanks=22&ts=1325861341).

However, when trying to use it I noticed that this (which I found in your CMakeLists.txt) didn't work:
find_package(UNITTEST++ REQUIRED)

until I changed it to:
find_package(UnitTest++ REQUIRED)

I don't know if this is a platform specific thing, but I am using Ubuntu 11.10 and CMake 2.8.5.

**Comment by gotthardp** [comment]
Oops. When working on Windows I always forget about the strange Linux systems. ;-) I made a fix in the "develop" branch.

**Comment by libamqp** [comment]
Hi David,

I'm only using the CMake build on Windows so the incorrect case didn't show
up. I'll fix that. I do my development work on a Mac and I'm using gmake to
do the build on MacOS ann on Linux (I test the build on 32-bit and 64-bit
Ubuntu 10.04 VMs).

Also, I've not spend much time on the Windows port recently. None of the
socket code has been ported to windows yet. Next month hopefully.

Are you able to build libamqp with CMake on Ubuntu?

regards,
Eamon

On 6 January 2012 14:47, David Doria <
reply@reply.github.com

> wrote:
> 
> I found your FindUnitTest++.cmake file, very nice! (I'll suggest to the
> UnitTest++ team that the include the file with their release).
> 
> However, when trying to use it I noticed that this (which I found in your
> CMakeLists.txt) didn't work:
> find_package(UNITTEST++ REQUIRED)
> 
> until I changed it to:
> find_package(UnitTest++ REQUIRED)
> 
> I don't know if this is a platform specific thing, but I am using Ubuntu
> 11.10 and CMake 2.8.5.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/libamqp/libamqp/issues/1

## 

Eamon Walshe
Technical Director
eamon.walshe@StormMQ.com
StormMQ Limited

UK Office:
Gateshead int'l Business Centre, Mulgrave Terrace, Gateshead, NE8 1AN,
United Kingdom
Telephone:   08453 712 567

Registered office:
16 Anchor Street, Chelmsford, Essex, CM2 0JY, United Kingdom
StormMQ Limited is Registered in England and Wales under Company Number
07175657

StormMQ.com

**Comment by daviddoria** [comment]
I actually have no intention of using libamqp, I just found your FindUnitTest++.cmake file :)

Just for fun I tried to build it for you, but immediately got "cannot find UnitTest++" error. I see in the README:
"UnitTest++ is required by the libamqp build and does not introduce a dependency on code linking with libamqp."

Since that is the case, you might consider automatically turning off UnitTest++ (as either a default or if it is not automatically found correctly). I know that many people very quickly dismiss projects if they run "cmake .; make" and there are errors :)

**Comment by gotthardp** [comment]
Hi,
I made a quick fix, but I admit that libamqp may not compile anyway since the CMakeFiles were not maintained for a while (my fault).

Petr

-----Original Message-----

**Comment by libamqp** [comment]
I stopped maintaining the Windows port when I began working on the
transport layer. I'll add a Jenkins build that runs the CMake build on
Linux.

On 6 January 2012 15:52, Petr Gotthard <
reply@reply.github.com

**Comment by gotthardp** [comment]
FIND_PACKAGE(UnitTest++) is used in devel branch
