### ISSUE TITLE
Disable UnitTest++ by default (or if not found)

### ISSUE THREAD

**Issue by daviddoria** [libamqp/libamqp#2]
Here is my build procedure:

~/src$ git clone https://github.com/libamqp/libamqp.git
Cloning into libamqp...
remote: Counting objects: 5499, done.
remote: Compressing objects: 100% (1968/1968), done.
remote: Total 5499 (delta 4372), reused 4624 (delta 3497)
Receiving objects: 100% (5499/5499), 3.72 MiB | 457 KiB/s, done.
Resolving deltas: 100% (4372/4372), done.
~/src$ cd libamqp/
~/src/libamqp$ git pull origin develop
From https://github.com/libamqp/libamqp
- branch            develop    -> FETCH_HEAD
  Already up-to-date.
  ~/src/libamqp$ mkdir build
  ~/src/libamqp$ cd build/
  ~/src/libamqp/build$ cmake ../
  -- The C compiler identification is GNU
  -- The CXX compiler identification is GNU
  -- Check for working C compiler: /usr/bin/gcc
  -- Check for working C compiler: /usr/bin/gcc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Could NOT find UnitTest++ (missing:  UNITTEST++_LIBRARY) 
  CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  UNITTEST++_LIBRARY
  linked by target "Test" in directory /home/doriad/src/libamqp/src

-- Configuring incomplete, errors occurred!

It would be great to make this work without having to setup UnitTest++ (for the typical user, who won't likely run the tests).

**Comment by gotthardp** [comment]
Fixed in af404f8412a940059fa54af0b25160bc94c8dd4b.
